version: '3'
services:
  mongodb:
    image: "mongo:3.2"
    ports:
     - "27017:27017"
  backend:
    image: pivoinetheone/arinf-backend:1.1
    ports:
      - "6200:6200"
    volumes:
      - ./backend:/usr/src/backend/app
      - "/usr/src/backend/app/node_modules"
    depends_on:
      - mongodb
  frontend:
    image: pivoinetheone/arinf-frontend:1.1
    ports:
      - "80:3000"
    volumes:
      - ./react-frontend:/usr/src/frontend/app
      - "/usr/src/frontend/app/node_modules"
    depends_on:
      - backend

